- apt_repository: repo='ppa:chris-lea/redis-server'
- apt: pkg='redis-server'

- name: Add redis.conf template
  template:
    src=templates/redis.conf.j2
    dest=/etc/redis/redis.conf
    owner=root group=root mode=0644
